name: 'Default Product'
description: 'Standard configuration enabling all modules'

# List of enabled modules
modules:
  - auth
  - example
  - insurance
  - permission
  - product
  - showcase

# Theme configuration (example)
theme:
  primary: '#1976D2'

# Meta configuration (SEO)
meta:
  title: '松凌科技前端架構系統'
  description: '松凌科技前端架構系統'
  favicon: '/favicon.jpg'
  themeColor: '#ffffff'
