name: 'Default Product'
description: 'Standard configuration enabling all modules'

# List of enabled modules
modules:
  - auth
  - example
  - insurance

  - product
  - showcase

# Theme configuration (example)
theme:
  primary: '#1976D2'

# Meta configuration (SEO)
meta:
  title: 'SoftLeader'
  description: 'SoftLeader'
  favicon: '/favicon.jpg'
  themeColor: '#ffffff'
